#!/usr/bin/env bash

# change to script's dir
#cd `dirname "$0"`

# uses the name of the script to restart the gunicorn instance

echo restarting server

# restart server
kill -HUP `cat /home/mathseminars/gunicorn.pid`

echo '... done'
