#!/usr/bin/env bash
echo 'Killing supervisord ...'
kill -TERM `cat /home/mathseminars/supervisord.pid`
rm /home/mathseminars/supervisord.pid
echo 'Killing gunicorn ...'
for branch in live stable master; do
  echo branch = $branch
  kill -TERM `cat /home/mathseminars/gunicorn-$branch.pid`
  rm /home/mathseminars/gunicorn-$branch.pid
done
echo '... and done!'
